# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s
steps:
- id: 'setup state bucket'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
  - '-c'
  - |-
    gsutil ls gs://$PROJECT_ID-tfstate || gsutil mb gs://$PROJECT_ID-tfstate
    (gsutil versioning get gs://$PROJECT_ID-tfstate | grep Enabled) || gsutil versioning set on gs://$PROJECT_ID-tfstate

- id: 'get machine type'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |-
      apt -qqy update && apt -qqy install jq
      (gcloud --format=json compute project-info describe | jq -e -r '.commonInstanceMetadata.items[] | select(.key == "radlab-machine-type") | .value' || printf "n2-standard-32") > /workspace/radlab_machine_type

- id: 'tf init'
  name: 'hashicorp/terraform:latest'
  env:
  - 'TF_CLI_ARGS_init=-backend-config=bucket=$PROJECT_ID-tfstate -backend-config=prefix=env/$BRANCH_NAME'
  - 'TF_VAR_project=$PROJECT_ID'
  - 'TF_VAR_env=$BRANCH_NAME'
  entrypoint: 'sh'
  args:
  - '-c'
  - |-
    terraform init

- id: 'tf import'
  name: 'hashicorp/terraform:latest'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  - 'TF_VAR_env=$BRANCH_NAME'
  entrypoint: 'sh'
  args:
  - '-c'
  - |-
    terraform state show google_project.radlab_project || terraform import google_project.radlab_project $PROJECT_ID

- id: 'tf plan'
  name: 'hashicorp/terraform:latest'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  - 'TF_VAR_env=$BRANCH_NAME'
  entrypoint: 'sh'
  args:
  - '-c'
  - |-
    export TF_VAR_machine_type=$(cat /workspace/radlab_machine_type)
    terraform plan

- id: 'tf apply'
  name: 'hashicorp/terraform:latest'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  - 'TF_VAR_env=$BRANCH_NAME'
  entrypoint: 'sh'
  args:
  - '-c'
  - |-
    apk --no-cache add \
      curl \
      python3
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-394.0.0-linux-x86_64.tar.gz
    tar -C / -xzf google-cloud-cli-394.0.0-linux-x86_64.tar.gz
    export PATH=$$PATH:/google-cloud-sdk/bin
    gcloud config set core/disable_usage_reporting true
    gcloud config set component_manager/disable_update_check true
    gcloud --version
    export TF_VAR_machine_type=$(cat /workspace/radlab_machine_type)
    terraform apply -auto-approve
